import SideBar from '~/components/layouts/sidebar'

import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import { GetStaticProps } from 'next'

import type { NextPage } from 'next'
import Head from 'next/head'

import Introduction from "~/components/sections/introduction"


const Home: NextPage = () => {
  return (
    <>
          <SideBar />
    <div className='flex-1 h-full bg-blue-300'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        sfsdfsdfsdfs
      </div>
    </div>
    </>
  )
}

export default Home

export const getStaticProps: GetStaticProps = async ({ locale }) => ({
  props: {
    ...await serverSideTranslations(locale!, ["sidebar", "locales"]),
  }
})